[project]
name = "ayon-openpype-import-processor"
version = "0.2.3"
description = ""
authors = ["Martastain <martas@imm.cz>"]
requires-python = ">=3.11,<3.12"

dependencies = [
  "pydantic ==1.10.18",
  "rich >=13.3.1",
  "nxtools >=1.6",
  "requests >=2.28"
]
